import HeaderMain from "../components/HeaderMain";
import HeaderTop from "../components/HeaderTop";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mayhem - Into reality",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
